<?php

return [
    'widgets' => [
        // ── Existing 11 widgets ──
        'stats_grid' => [
            'name' => 'Статистика',
            'description' => '4 KPI картки: люди, служіння, групи, події',
            'icon' => 'chart-bar',
            'default_cols' => 12,
            'min_cols' => 12,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.stats-grid',
        ],
        'birthdays' => [
            'name' => 'Дні народження',
            'description' => 'Іменинники за обраний місяць',
            'icon' => 'cake',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.birthdays',
        ],
        'pending_assignments' => [
            'name' => 'Очікує підтвердження',
            'description' => 'Призначення, що очікують відповіді',
            'icon' => 'clock',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.pending-assignments',
        ],
        'upcoming_events' => [
            'name' => 'Найближчі події',
            'description' => 'Заплановані події на найближчі 7 днів',
            'icon' => 'calendar',
            'default_cols' => 8,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.upcoming-events',
        ],
        'attendance_chart' => [
            'name' => 'Відвідуваність',
            'description' => 'Графік відвідуваності за 4 тижні',
            'icon' => 'chart-line',
            'default_cols' => 4,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.attendance-chart',
        ],
        'analytics_charts' => [
            'name' => 'Аналітика',
            'description' => 'Графіки зростання, фінансів, відвідуваності, служінь',
            'icon' => 'chart-pie',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.analytics-charts',
        ],
        'financial_summary' => [
            'name' => 'Фінансовий підсумок',
            'description' => 'Доходи, витрати, баланс за місяць',
            'icon' => 'banknotes',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.financial-summary',
        ],
        'ministry_budgets' => [
            'name' => 'Бюджети команд',
            'description' => 'Прогрес виконання бюджетів служінь',
            'icon' => 'currency-dollar',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.ministry-budgets',
        ],
        'expenses_breakdown' => [
            'name' => 'Витрати за місяць',
            'description' => 'Розбивка витрат по категоріях',
            'icon' => 'receipt-percent',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.expenses-breakdown',
        ],
        'need_attention' => [
            'name' => 'Потребують уваги',
            'description' => 'Люди, що не відвідували 3+ тижні',
            'icon' => 'exclamation-triangle',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.need-attention',
        ],
        'urgent_tasks' => [
            'name' => 'Термінові завдання',
            'description' => 'Термінові та прострочені завдання з трекера',
            'icon' => 'clipboard-document-check',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.urgent-tasks',
        ],

        // ── 20 New widgets ──
        'prayer_requests' => [
            'name' => 'Молитовні потреби',
            'description' => 'Активні молитовні прохання громади',
            'icon' => 'heart',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.prayer-requests',
        ],
        'announcements' => [
            'name' => 'Оголошення',
            'description' => 'Останні оголошення та новини',
            'icon' => 'megaphone',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.announcements',
        ],
        'donation_campaigns' => [
            'name' => 'Збори коштів',
            'description' => 'Активні кампанії зі збору коштів',
            'icon' => 'gift',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.donation-campaigns',
        ],
        'ministry_goals' => [
            'name' => 'Цілі служінь',
            'description' => 'Прогрес цілей по командах',
            'icon' => 'flag',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.ministry-goals',
        ],
        'recent_sermons' => [
            'name' => 'Останні проповіді',
            'description' => 'Нещодавно опубліковані проповіді',
            'icon' => 'microphone',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.recent-sermons',
        ],
        'member_demographics' => [
            'name' => 'Демографія',
            'description' => 'Розподіл за віком та статтю',
            'icon' => 'user-group',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.member-demographics',
        ],
        'new_members' => [
            'name' => 'Нові люди',
            'description' => 'Нещодавно додані люди до бази',
            'icon' => 'user-plus',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.new-members',
        ],
        'group_health' => [
            'name' => 'Здоров\'я груп',
            'description' => 'Відвідуваність та активність малих груп',
            'icon' => 'users',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.group-health',
        ],
        'giving_trends' => [
            'name' => 'Тренди пожертв',
            'description' => 'Графік пожертв за останні 6 місяців',
            'icon' => 'arrow-trending-up',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.giving-trends',
        ],
        'shepherd_overview' => [
            'name' => 'Пастирство',
            'description' => 'Огляд пастирських призначень',
            'icon' => 'shield-check',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.shepherd-overview',
        ],
        'event_registrations' => [
            'name' => 'Реєстрації на події',
            'description' => 'Найближчі події з відкритою реєстрацією',
            'icon' => 'ticket',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.event-registrations',
        ],
        'quick_actions' => [
            'name' => 'Швидкі дії',
            'description' => 'Кнопки для частих дій адміністратора',
            'icon' => 'bolt',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.quick-actions',
        ],
        'volunteer_schedule' => [
            'name' => 'Розклад служителів',
            'description' => 'Хто служить на найближчих подіях',
            'icon' => 'calendar-days',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.volunteer-schedule',
        ],
        'recent_activity' => [
            'name' => 'Остання активність',
            'description' => 'Нещодавні дії в системі',
            'icon' => 'clock',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.recent-activity',
        ],
        'membership_funnel' => [
            'name' => 'Воронка членства',
            'description' => 'Розподіл людей за статусом членства',
            'icon' => 'funnel',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.membership-funnel',
        ],
        'popular_songs' => [
            'name' => 'Популярні пісні',
            'description' => 'Найчастіше використовувані пісні',
            'icon' => 'musical-note',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.popular-songs',
        ],
        'family_stats' => [
            'name' => 'Сім\'ї',
            'description' => 'Огляд сімейних зв\'язків у громаді',
            'icon' => 'home',
            'default_cols' => 4,
            'min_cols' => 3,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.family-stats',
        ],
        'calendar_mini' => [
            'name' => 'Календар',
            'description' => 'Міні-календар з відмітками подій',
            'icon' => 'calendar',
            'default_cols' => 4,
            'min_cols' => 3,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.calendar-mini',
        ],
        'online_donations' => [
            'name' => 'Онлайн пожертви',
            'description' => 'Статистика онлайн платежів',
            'icon' => 'credit-card',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => false,
            'requires_permission' => 'finances',
            'partial' => 'dashboard.widgets.online-donations',
        ],
        'group_attendance_compare' => [
            'name' => 'Порівняння груп',
            'description' => 'Порівняння відвідуваності малих груп',
            'icon' => 'chart-bar-square',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.group-attendance-compare',
        ],
    ],
];
