<?php

return [
    'widgets' => [
        'stats_grid' => [
            'name' => 'Статистика',
            'description' => '4 KPI картки: люди, служіння, групи, події',
            'icon' => 'chart-bar',
            'default_cols' => 12,
            'min_cols' => 12,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.stats-grid',
        ],
        'birthdays' => [
            'name' => 'Дні народження',
            'description' => 'Іменинники за обраний місяць',
            'icon' => 'cake',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.birthdays',
        ],
        'pending_assignments' => [
            'name' => 'Очікує підтвердження',
            'description' => 'Призначення, що очікують відповіді',
            'icon' => 'clock',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.pending-assignments',
        ],
        'upcoming_events' => [
            'name' => 'Найближчі події',
            'description' => 'Заплановані події на найближчі 7 днів',
            'icon' => 'calendar',
            'default_cols' => 8,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.upcoming-events',
        ],
        'attendance_chart' => [
            'name' => 'Відвідуваність',
            'description' => 'Графік відвідуваності за 4 тижні',
            'icon' => 'chart-line',
            'default_cols' => 4,
            'min_cols' => 4,
            'admin_only' => false,
            'partial' => 'dashboard.widgets.attendance-chart',
        ],
        'analytics_charts' => [
            'name' => 'Аналітика',
            'description' => 'Графіки зростання, фінансів, відвідуваності, служінь',
            'icon' => 'chart-pie',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.analytics-charts',
        ],
        'financial_summary' => [
            'name' => 'Фінансовий підсумок',
            'description' => 'Доходи, витрати, баланс за місяць',
            'icon' => 'banknotes',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.financial-summary',
        ],
        'ministry_budgets' => [
            'name' => 'Бюджети команд',
            'description' => 'Прогрес виконання бюджетів служінь',
            'icon' => 'currency-dollar',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.ministry-budgets',
        ],
        'expenses_breakdown' => [
            'name' => 'Витрати за місяць',
            'description' => 'Розбивка витрат по категоріях',
            'icon' => 'receipt-percent',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.expenses-breakdown',
        ],
        'need_attention' => [
            'name' => 'Потребують уваги',
            'description' => 'Люди, що не відвідували 3+ тижні',
            'icon' => 'exclamation-triangle',
            'default_cols' => 6,
            'min_cols' => 4,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.need-attention',
        ],
        'urgent_tasks' => [
            'name' => 'Термінові завдання',
            'description' => 'Термінові та прострочені завдання з трекера',
            'icon' => 'clipboard-document-check',
            'default_cols' => 12,
            'min_cols' => 6,
            'admin_only' => true,
            'partial' => 'dashboard.widgets.urgent-tasks',
        ],
    ],
];
